
# colors that users can get. If more users than colors are used, colors have to be extended
available_colors: ['00FF0000','0000FF00','000000FF','00FFFF00','00FF00FF','0000FFFF','00008000','00008080','00800080','009999FF','00FFFFCC','00FF8080','00CCCCFF','0099CC00','00FFCC00','00FF9900','00FF6600','00993300']

# output file name
excel_file_name: "kalender.xlsx"

# local for printing localized dates
locale: "de_DE"

# manual override of year, default is datetime.date.today().year
# year_for_calendar: 2024

# list of users that should appear in the excel file
users:
  - name: "Marcel"
    vacation_dates:
      - { "begin" : "01.01.2024", "end" : "02.01.2024" }
  - name: "Antje"
    vacation_dates:
      - { "begin" : "01.01.2024", "end" : "02.01.2024" }

### OPENHOLIDAYSAPI
oh_api_base_url: "https://openholidaysapi.org/"

oh_api_country_iso_code: "DE"

oh_api_language_iso_code: "DE"

oh_api_subdivision_code: "DE-BE"

# should holidays be shown in the excel?
oh_api_show_holidays: True

# holidays are shown with this name
oh_api_show_name: "Schulferien Berlin"

# show holidays with this color
oh_api_show_color: "EFaaEF"

